### ISSUE TITLE
As a user, I want to filter my results by category

### ISSUE THREAD

**Issue by ghost** [codegnv/business-web#42] opened 2016-11-01 23:23 UTC
Possible filters:
- Business category
- Business type
- Permit type

Refer to comps:
https://www.dropbox.com/s/b4vcpak4dvqjux8/Home.png?dl=0
https://www.dropbox.com/s/86f7walarvqrp2a/Search%20Results.png?dl=0

**Comment by Bjorn248** [comment] 2016-11-04 02:38
Duplicate of #33 ?

**Comment by ghost** [comment] 2016-11-04 02:42
Maybe? This is about the `Refine Your Results` area to the left of the search results.

**Comment by samanthawolfe** [comment] 2016-11-29 23:18
When filtering, Business Types should fall under specific Business Category. Instead, Types are falling to bottom of entire Category list. 
![image](https://cloud.githubusercontent.com/assets/19419412/20733225/3371e922-b660-11e6-9cfa-1e9113cbe62f.png)

**Comment by Bjorn248** [comment] 2016-12-05 18:31
@samanthawolfe is this resolved in the latest version of the site?

**Comment by samanthawolfe** [comment] 2016-12-06 17:18
Yes; I think so.

**Closed as completed by samanthawolfe** 2016-12-06 17:18 UTC
