### ISSUE TITLE
Icons representing each step in the process not displaying

### ISSUE THREAD

**Issue by samanthawolfe** [codegnv/business-web#197] opened 2017-10-10 13:52 UTC
## Steps to Reproduce

1. Visit homepage and any content page
2. Icons do not display

## Expected Behavior

View each icon, that is clickable, and links to a content page.

## Actual Behavior

Icon image is not displaying.

![image](https://user-images.githubusercontent.com/19419412/31390011-bad7d006-ada0-11e7-8314-6b5d12c1087a.png)

**Comment by Bjorn248** [comment] 2017-10-10 13:53
Duplicate of #196, closing

**Comment by samanthawolfe** [comment] 2017-10-10 13:53
You are a step ahead of me, @Bjorn248!

**Closed as completed by Bjorn248** 2017-10-10 13:53 UTC
Labels: bug
